Dzangocart\Bundle\SubscriptionBundle\Propel\Feature:
    properties:
        property_name:
            - NotNull:
                message: feature.validation.error.property_name._null
            - NotBlank:
                message: feature.validation.error.property_name.blank
            - Dzangocart\Bundle\SubscriptionBundle\Validator\Constraints\AlphaNumeric:
                message: feature.validation.error.property_name.alphanumeric
