Dzangocart\Bundle\SubscriptionBundle\Model\AccountInterface:
    properties:
        plan_id:
            - NotNull:
                message: account.plan_id.null

Dzangocart\Bundle\SubscriptionBundle\Propel\Feature:
    properties:
        property_name:
            - NotNull:
                message: feature.property_name._null
            - NotBlank:
                message: feature.property_name.blank
            - Dzangocart\Bundle\SubscriptionBundle\Validator\Constraints\AlphaNumeric:
                message: feature.property_name.alphanumeric

Dzangocart\Bundle\SubscriptionBundle\Propel\Plan:
    constraints:
        - Dzangocart\Bundle\SubscriptionBundle\Validator\Constraints\PlanPeriod: ~
