services:
    dzangocart.subscription.factory.propel:
        class: Dzangocart\Bundle\SubscriptionBundle\Propel\SubscriptionFactory
        arguments:
            - "%dzangocart.subscription.account_class%"
