services:

    dzangocart.subscription.signup.form.type:
        class:  Dzangocart\Bundle\SubscriptionBundle\Form\Type\SignupFormType
        arguments:
            - @request_stack
            - %dzangocart.subscription.signup.class%
            - %dzangocart.subscription.trial.config%
        tags:
            - { name: form.type, alias: dzangocart_subscription_signup }
