stages:
    - php70
    - php56
    - php55

php7.0:
    image: unitedasian/php:7.0
    script:
        - composer update
    stage: php70
    tags:
        - php70

php5.6:
    image: unitedasian/php:5.6
    script:
        - composer update
    stage: php56
    tags:
        - php56

php5.5:
    image: unitedasian/php:5.5
    script:
        - composer update
    stage: php55
    tags:
        - php55
