dzangocart_subscription_feature:
    resource: "@DzangocartSubscriptionBundle/Controller/FeatureController.php"
    type: annotation

dzangocart_subscription_plan:
    resource: "@DzangocartSubscriptionBundle/Resources/config/routing/plan.yml"