dzangocart_subscription_pricing:
    pattern: /pricing
    defaults: { _controller: DzangocartSubscriptionBundle:Pricing:index }

dzangocart_subscription_matrix:
    resource: "@DzangocartSubscriptionBundle/Controller/MatrixController.php"
    type: annotation
    
dzangocart_subscription_signup:
    pattern: /signup
    defaults: { _controller: dzangocart_subscription.signup.controller:signupAction}
    
