dzangocart_subscription_pricing:
    resource: "@DzangocartSubscriptionBundle/Resources/config/routing/pricing.xml"

dzangocart_subscription_matrix:
    resource: "@DzangocartSubscriptionBundle/Resources/config/routing/matrix.xml"

dzangocart_subscription_signup:
    path: /signup
    defaults: { _controller: dzangocart_subscription.signup.controller:signupAction}
