dzangocart_subscription_pricing:
    path: /pricing
    defaults: { _controller: DzangocartSubscriptionBundle:Pricing:index }

_dzangocart_subscription_matrix:
    resource: "@DzangocartSubscriptionBundle/Resources/config/routing/matrix.xml"

dzangocart_subscription_signup:
    path: /signup
    defaults: { _controller: dzangocart_subscription.signup.controller:signupAction}
