dzangocart_subscription_plans:
    path: /plan
    defaults: { _controller: dzangocartsubscription.plan.controller:indexAction}

dzangocart_subscription_plan:
    path: /plan/{id}
    defaults: { _controller: dzangocartsubscription.plan.controller:showAction}
    requirements:
        id: \d+

dzangocart_subscription_plan_edit:
    path: /plan/{id}/edit
    defaults: { _controller: dzangocartsubscription.plan.controller:editAction}
    requirements:
        id: \d+

dzangocart_subscription_plan_delete:
    path: /plan/{id}/delete
    defaults: { _controller: dzangocartsubscription.plan.controller:deleteAction}
    requirements:
        id: \d+

dzangocart_subscription_plan_create:
    path: /plan/create
    defaults: { _controller: dzangocartsubscription.plan.controller:createAction}

dzangocart_subscription_plan_disable:
    path: /plan/{id}/disable
    defaults: { _controller: dzangocartsubscription.plan.controller:disableAction}
    requirements:
        id: \d+

dzangocart_subscription_plan_use_default_for_trial:
    path: /plan/{id}/default
    defaults: { _controller: dzangocartsubscription.plan.controller:setDefaultAction}
    requirements:
        id: \d+

dzangocart_subscription_plan_remove_default_for_trial:
    path: /plan/{id}/removedefault
    defaults: { _controller: dzangocartsubscription.plan.controller:removeDefaultAction}
    requirements:
        id: \d+

dzangocart_subscription_plan_enable:
    path: /plan/{id}/enable
    defaults: { _controller: dzangocartsubscription.plan.controller:enableAction}
    requirements:
        id: \d+

dzangocart_subscription_plan_features:
    path: /plan/{id}/features
    defaults: { _controller: dzangocartsubscription.plan.controller:featuresAction}
    requirements:
        id: \d+

dzangocart_subscription_plan_prices:
    path: /plan/{id}/prices
    defaults: { _controller: dzangocartsubscription.plan.controller:pricesAction}
    requirements:
        id: \d+

dzangocart_subscription_plan_ranks_change:
    path: /plan/rank/change
    defaults: { _controller: dzangocartsubscription.plan.controller:changeRankAction}
